services:
  postgres:
    image: postgres:17.9-alpine3.23
    environment:
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  adminer:
    image: adminer:5.4.2-standalone
    ports:
      - "5050:8080"

  backup:
    build: ./backup
    environment:
      TZ: Europe/Helsinki
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: testing
      CRON_SCHEDULE: "* * * * *"
      AGE_RECIPIENT: ${AGE_RECIPIENT}
      HEALTHCHECK_URL: ${HEALTHCHECK_URL}
    volumes:
      - ./output:/backups
      - ./begin.sh:/hooks/pre/begin.sh:ro
      - ./done.sh:/hooks/post/done.sh:ro
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: